"""initial schema

Revision ID: d9057289416c
Revises:
Create Date: 2026-07-28 19:54:10.574980
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d9057289416c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video_assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("hashed_case_id", sa.String(length=64), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("safe_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("fps", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("codec", sa.String(length=64), nullable=True),
        sa.Column("audio_present", sa.Boolean(), nullable=True),
        sa.Column("original_uri", sa.Text(), nullable=True),
        sa.Column("proxy_uri", sa.Text(), nullable=True),
        sa.Column("thumbnail_uri", sa.Text(), nullable=True),
        sa.Column("original_sha256", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("review_revision", sa.Integer(), nullable=False),
        sa.Column("active_model_run_id", sa.String(length=36), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("original_sha256"),
    )
    op.create_table(
        "model_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("detector_versions", sa.JSON(), nullable=False),
        sa.Column("tracker_name", sa.String(length=64), nullable=False),
        sa.Column("tracker_version", sa.String(length=64), nullable=False),
        sa.Column("thresholds", sa.JSON(), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("device", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["video_id"], ["video_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_model_runs_video_id"), "model_runs", ["video_id"], unique=False)
    op.create_table(
        "review_actions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("track_id", sa.String(length=36), nullable=True),
        sa.Column("frame_index", sa.Integer(), nullable=True),
        sa.Column("timestamp_ms", sa.Integer(), nullable=True),
        sa.Column("action_type", sa.String(length=40), nullable=False),
        sa.Column("before_state", sa.JSON(), nullable=False),
        sa.Column("after_state", sa.JSON(), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("reviewer_session_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("model_version", sa.String(length=128), nullable=True),
        sa.Column("application_version", sa.String(length=32), nullable=False),
        sa.Column("inverse_of_action_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["inverse_of_action_id"], ["review_actions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["video_id"], ["video_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_id", "revision", name="uq_review_action_revision"),
    )
    op.create_index(
        op.f("ix_review_actions_track_id"), "review_actions", ["track_id"], unique=False
    )
    op.create_index(
        "ix_review_actions_video_created",
        "review_actions",
        ["video_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_actions_video_id"), "review_actions", ["video_id"], unique=False
    )
    op.create_table(
        "detections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("model_run_id", sa.String(length=36), nullable=False),
        sa.Column("frame_index", sa.Integer(), nullable=False),
        sa.Column("timestamp_ms", sa.Integer(), nullable=False),
        sa.Column("class_name", sa.String(length=48), nullable=False),
        sa.Column("x1", sa.Float(), nullable=False),
        sa.Column("y1", sa.Float(), nullable=False),
        sa.Column("x2", sa.Float(), nullable=False),
        sa.Column("y2", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("detector_name", sa.String(length=64), nullable=False),
        sa.Column("detector_version", sa.String(length=64), nullable=False),
        sa.Column("proposal_source", sa.String(length=24), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("inference_ms", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["model_run_id"], ["model_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["video_id"], ["video_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_detections_model_run_id"), "detections", ["model_run_id"], unique=False
    )
    op.create_index(
        "ix_detections_run_class", "detections", ["model_run_id", "class_name"], unique=False
    )
    op.create_index(
        "ix_detections_video_frame", "detections", ["video_id", "frame_index"], unique=False
    )
    op.create_index(op.f("ix_detections_video_id"), "detections", ["video_id"], unique=False)
    op.create_table(
        "export_artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("export_uri", sa.Text(), nullable=True),
        sa.Column("export_sha256", sa.String(length=64), nullable=True),
        sa.Column("manifest_uri", sa.Text(), nullable=True),
        sa.Column("redaction_style", sa.String(length=24), nullable=False),
        sa.Column("source_model_run_id", sa.String(length=36), nullable=True),
        sa.Column("review_revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["source_model_run_id"], ["model_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["video_id"], ["video_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "video_id", "review_revision", "redaction_style", name="uq_export_revision_style"
        ),
    )
    op.create_index(
        op.f("ix_export_artifacts_video_id"), "export_artifacts", ["video_id"], unique=False
    )
    op.create_table(
        "tracks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("model_run_id", sa.String(length=36), nullable=True),
        sa.Column("class_name", sa.String(length=48), nullable=False),
        sa.Column("start_frame", sa.Integer(), nullable=False),
        sa.Column("end_frame", sa.Integer(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("default_redacted", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("confidence_summary", sa.JSON(), nullable=False),
        sa.Column("parent_track_id", sa.String(length=36), nullable=True),
        sa.Column("reviewed_until_frame", sa.Integer(), nullable=True),
        sa.Column("warning", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["model_run_id"], ["model_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_track_id"], ["tracks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["video_id"], ["video_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tracks_model_run_id"), "tracks", ["model_run_id"], unique=False)
    op.create_index(op.f("ix_tracks_video_id"), "tracks", ["video_id"], unique=False)
    op.create_index(
        "ix_tracks_video_span", "tracks", ["video_id", "start_frame", "end_frame"], unique=False
    )
    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=True),
        sa.Column("export_id", sa.String(length=36), nullable=True),
        sa.Column("job_type", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("stage", sa.String(length=80), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["export_id"], ["export_artifacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["video_id"], ["video_assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processing_jobs_video_id"), "processing_jobs", ["video_id"], unique=False
    )
    op.create_index(
        "ix_processing_jobs_video_status", "processing_jobs", ["video_id", "status"], unique=False
    )
    op.create_table(
        "track_keyframes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("track_id", sa.String(length=36), nullable=False),
        sa.Column("frame_index", sa.Integer(), nullable=False),
        sa.Column("timestamp_ms", sa.Integer(), nullable=False),
        sa.Column("x1", sa.Float(), nullable=False),
        sa.Column("y1", sa.Float(), nullable=False),
        sa.Column("x2", sa.Float(), nullable=False),
        sa.Column("y2", sa.Float(), nullable=False),
        sa.Column("interpolation_mode", sa.String(length=24), nullable=False),
        sa.Column("visibility", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("track_id", "frame_index", "source", name="uq_track_keyframe_source"),
    )
    op.create_index(
        op.f("ix_track_keyframes_track_id"), "track_keyframes", ["track_id"], unique=False
    )
    op.create_index(
        "ix_track_keyframes_track_time",
        "track_keyframes",
        ["track_id", "timestamp_ms"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_track_keyframes_track_time", table_name="track_keyframes")
    op.drop_index(op.f("ix_track_keyframes_track_id"), table_name="track_keyframes")
    op.drop_table("track_keyframes")
    op.drop_index("ix_processing_jobs_video_status", table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_video_id"), table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_index("ix_tracks_video_span", table_name="tracks")
    op.drop_index(op.f("ix_tracks_video_id"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_model_run_id"), table_name="tracks")
    op.drop_table("tracks")
    op.drop_index(op.f("ix_export_artifacts_video_id"), table_name="export_artifacts")
    op.drop_table("export_artifacts")
    op.drop_index(op.f("ix_detections_video_id"), table_name="detections")
    op.drop_index("ix_detections_video_frame", table_name="detections")
    op.drop_index("ix_detections_run_class", table_name="detections")
    op.drop_index(op.f("ix_detections_model_run_id"), table_name="detections")
    op.drop_table("detections")
    op.drop_index(op.f("ix_review_actions_video_id"), table_name="review_actions")
    op.drop_index("ix_review_actions_video_created", table_name="review_actions")
    op.drop_index(op.f("ix_review_actions_track_id"), table_name="review_actions")
    op.drop_table("review_actions")
    op.drop_index(op.f("ix_model_runs_video_id"), table_name="model_runs")
    op.drop_table("model_runs")
    op.drop_table("video_assets")
    # ### end Alembic commands ###
