steps:
  - id: api
    name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - --file=docker/api.Dockerfile
      - --tag=${_API_IMAGE}
      - .
  - id: gpu-worker
    name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - --file=docker/gpu-worker.Dockerfile
      - --tag=${_GPU_IMAGE}
      - .
  - id: web
    name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      - build
      - --file=docker/web.Dockerfile
      - --tag=${_WEB_IMAGE}
      - .
images:
  - ${_API_IMAGE}
  - ${_GPU_IMAGE}
  - ${_WEB_IMAGE}
options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
timeout: 2400s
